### ISSUE TITLE
Decision of the license type

### ISSUE THREAD

**Issue by demirhancosku** [demirhancosku/cryptoradar#1]
What type of license type will be more suitable for this project?

**Comment by ernyldrm** [comment]
GNU General Public License v3.0 and future versions are selected as the license of this package.

The GNU General Public License does not permit incorporating your program
into proprietary programs.  If your program is a subroutine library, you
may consider it more useful to permit linking proprietary applications with
the library.  If this is what you want to do, use the GNU Lesser General
Public License instead of this License.  But first, please read
<http://www.gnu.org/philosophy/why-not-lgpl.html>.
